grafana:
  grafana.ini:
    server:
      # Define how Grafana is accessed externally
      # You may need to adjust this based on your ingress or NodePort setup
      root_url: "http://localhost:3000/"
    auth:
      disable_login_form: false
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      client_id: [YOUR_CLIENT]
      client_secret: [YOUR_SECRET]
      scopes: openid email profile
      # auth_url must be accessible from the user's browser
      auth_url: http://localhost:30080/realms/test-realm/protocol/openid-connect/auth
      # token_url and api_url are server-to-server communications
      token_url: http://keycloak.keycloak.svc.cluster.local:80/realms/test-realm/protocol/openid-connect/token
      api_url: http://keycloak.keycloak.svc.cluster.local:80/realms/test-realm/protocol/openid-connect/userinfo
      role_attribute_path: contains(realm_access.roles[*], 'admin') && 'Admin' || contains(realm_access.roles[*], 'editor') && 'Editor' || 'Viewer'
      login_attribute_path: preferred_username
      name_attribute_path: name
      email_attribute_path: email
    users:
      auto_assign_org: true
      auto_assign_org_id: 1
      auto_assign_org_role: Viewer